language: node_js
sudo: required
node_js:
  - "7"

addons:
  chrome: stable

install:
  - npm install
  - npm install -g codecov

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

after_success:
  - codecov --token=92f20e77-5c1c-4f39-ab4b-bac2a5915136

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always